org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
# Override Kotlin JVM target for all Kotlin compilations
kotlin.jvm.target.validation.mode=warning
kotlin.code.style=official
# Set Kotlin JVM target version to 11
android.kotlinOptions.jvmTarget=11
# Add these lines to ensure compatibility
kotlin.stdlib.default.dependency=true

# Force Gradle to use the bundled Java 17+ from Android Studio instead of the system's default Java 8
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
